### ISSUE TITLE
RPI 1 B irqbalance restarted

### ISSUE THREAD

**Issue by markusressel** [homematic-community/hm-watchdog#22]
I recently "downgraded" from a RPI3 B+ to an RPI1 B+ for my RaspberryMatic setup (for reasons that do not matter here). Although the webinterface is now noticeably slower the switch worked seamless so far, except that I get this alert again and again until the whole unit restarts:

```
hm-watchdog: irqbalance restarted
```

For reference:
RaspberryMatic v3.47.18.20190918 was used on the RPI3 and is as well on the RPI1 now
hm-watchdog version 0.8 was also used on the RPI3 as well as the RP1 now

After importing the backup I deleted and reinstalled hm-watchdog v0.8 on **both** devices. I initially had issues with it on the RPI3 but that was probably because I still used v0.6. I had no issues when updating to 0.8 on the RPI3. The same version causes the issue mentioned above on the RPI1 B+ though.

I have no clue what causes this. Is it just the slower hardware that trips the "ping" check too soon? Anything I can contribute to help figure out what is going wrong?

**Comment by jens-maus** [comment]
irqbalance is not required/started for a RaspberryPi1. Thus hm-watchdog is wrong to warn you about this.

But BTW: With latest RaspberryMatic you don't really need hm-watchdog anymore because RaspberryMatic comes with an own internal watchdog mechanism (called 'monit'). Thus, the suggestion is to remove hm-watchdog if you use one of the latest RaspberryMatic versions.

**Comment by markusressel** [comment]
Thx for the quick response. I will just uninstall the watchdog then.
